
[info]
description = "Adding value by being authentic, creative, disciplined and curious. A husband, father, engineer, explorer and creator."
title404 = "Nothing's here!"

[assets]
favicon = "icons/favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[copyright]
prefix = ""
holder = "Ian Teda"
startYear = "1977"
suffix = ""

[settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#E1341E"
hideMainMenu = false

[sidebar]
enable = true

[widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[opengraph.twitter]
page = "" # Twitter page username

[seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[social]
# codepen = "MunifTanjim"
email = "ian@teda.id.au"
facebook = "ian.teda"
github = "IanTeda"
# gitlab = "MunifTanjim"
instagram = "IanTeda"
linkedin = "in/IanTeda/"
twitter = "IanTeda"
# telegram = "MunifTanjim"
# google_scholar = "qc6CJjYAAAAJ"
youtube = "UCzcdoQynrQ2rXOrBeKYyeig"

[comments]
enable = false

# Isso: https://posativ.org/isso/
[comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "MunifTanjim"
repository = "minimo"

# Utterances: https://utteranc.es
[comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[search]
client = "fuse" # algolia / fuse / lunr

[search.algolia]
appId = ""
indexName = ""
searchApiKey = ""