#-- .github/workflows/hugo.yaml
# This workflow builds a Hugo site and deploys it to GitHub Pages. It is triggered 
# on pushes to the main branch and can also be run manually. The workflow consists 
# of two jobs: build and deploy.
#
# The build job checks out the repository, sets up Hugo, installs Node.js dependencies,
# builds the site, and uploads the artifact. 
#
# The deploy job deploys the built site to GitHub Pages.
#
# The workflow uses the latest version of Ubuntu as the runner and sets permissions 
# for contents, pages, and id-token. The concurrency group is set to "pages" to 
# prevent multiple deployments from running simultaneously.

name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          fi

      - name: Build with Hugo
        run: hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4